import type { NewsItem } from '../types/news';

const now = new Date();
const minutesAgo = (m: number) => new Date(now.getTime() - m * 60 * 1000).toISOString();

export const MOCK_NEWS: NewsItem[] = [
  {
    id: 'mock-01',
    title: '【速報】北海道で震度5強の地震 津波の心配なし',
    link: 'https://example.com/news/1',
    source: 'nhk',
    publishedAt: minutesAgo(5),
    prefectureCode: '01',
    prefectureName: '北海道',
    isBreaking: true,
    category: 'disaster',
    ogpImageUrl: 'https://placehold.co/600x315/0a0a1a/ff3030?text=EARTHQUAKE+Hokkaido',
  },
  {
    id: 'mock-02',
    title: '仙台市で大規模再開発計画が始動 2030年完成予定',
    link: 'https://example.com/news/2',
    source: 'nhk',
    publishedAt: minutesAgo(30),
    prefectureCode: '04',
    prefectureName: '宮城県',
    isBreaking: false,
    category: 'other',
  },
  {
    id: 'mock-03',
    title: '東京都 新たな子育て支援策を発表 来月から実施',
    link: 'https://example.com/news/3',
    source: 'nhk',
    publishedAt: minutesAgo(45),
    prefectureCode: '13',
    prefectureName: '東京都',
    isBreaking: false,
    category: 'politics',
    ogpImageUrl: 'https://placehold.co/600x315/0a0a1a/00ffff?text=Tokyo+Policy',
  },
  {
    id: 'mock-04',
    title: '【緊急】大阪府で記録的大雨 避難指示発令',
    link: 'https://example.com/news/4',
    source: 'nhk',
    publishedAt: minutesAgo(10),
    prefectureCode: '27',
    prefectureName: '大阪府',
    isBreaking: true,
    category: 'disaster',
    ogpImageUrl: 'https://placehold.co/600x315/0a0a1a/ff3030?text=RAIN+Osaka',
  },
  {
    id: 'mock-05',
    title: '名古屋グランパス リーグ戦3連勝で首位浮上',
    link: 'https://example.com/news/5',
    source: 'nhk',
    publishedAt: minutesAgo(60),
    prefectureCode: '23',
    prefectureName: '愛知県',
    isBreaking: false,
    category: 'sports',
  },
  {
    id: 'mock-06',
    title: '福岡市 半導体産業誘致に新たな補助金制度',
    link: 'https://example.com/news/6',
    source: 'nhk',
    publishedAt: minutesAgo(90),
    prefectureCode: '40',
    prefectureName: '福岡県',
    isBreaking: false,
    category: 'politics',
    ogpImageUrl: 'https://placehold.co/600x315/0a0a1a/00ffff?text=Fukuoka+Tech',
  },
  {
    id: 'mock-07',
    title: '広島 原爆ドーム周辺の整備事業が完了',
    link: 'https://example.com/news/7',
    source: 'nhk',
    publishedAt: minutesAgo(120),
    prefectureCode: '34',
    prefectureName: '広島県',
    isBreaking: false,
    category: 'other',
  },
  {
    id: 'mock-08',
    title: '沖縄県 観光客数が過去最高を更新 インバウンド好調',
    link: 'https://example.com/news/8',
    source: 'nhk',
    publishedAt: minutesAgo(150),
    prefectureCode: '47',
    prefectureName: '沖縄県',
    isBreaking: false,
    category: 'other',
  },
  {
    id: 'mock-09',
    title: '京都で国際会議開催 AI技術の倫理指針を議論',
    link: 'https://example.com/news/9',
    source: 'nhk',
    publishedAt: minutesAgo(180),
    prefectureCode: '26',
    prefectureName: '京都府',
    isBreaking: false,
    category: 'other',
  },
  {
    id: 'mock-10',
    title: '新潟県 豪雪による交通障害が続く 自衛隊が除雪支援',
    link: 'https://example.com/news/10',
    source: 'nhk',
    publishedAt: minutesAgo(25),
    prefectureCode: '15',
    prefectureName: '新潟県',
    isBreaking: false,
    category: 'disaster',
  },
  {
    id: 'mock-11',
    title: '静岡県 富士山噴火対策の避難訓練を実施',
    link: 'https://example.com/news/11',
    source: 'nhk',
    publishedAt: minutesAgo(200),
    prefectureCode: '22',
    prefectureName: '静岡県',
    isBreaking: false,
    category: 'disaster',
  },
  {
    id: 'mock-12',
    title: '【速報】神戸市で建物火災 消防車20台以上が出動',
    link: 'https://example.com/news/12',
    source: 'nhk',
    publishedAt: minutesAgo(8),
    prefectureCode: '28',
    prefectureName: '兵庫県',
    isBreaking: true,
    category: 'disaster',
    ogpImageUrl: 'https://placehold.co/600x315/0a0a1a/ff8800?text=FIRE+Kobe',
  },
  {
    id: 'mock-13',
    title: '長野県 スキーリゾートが今季最高の入場者数を記録',
    link: 'https://example.com/news/13',
    source: 'nhk',
    publishedAt: minutesAgo(240),
    prefectureCode: '20',
    prefectureName: '長野県',
    isBreaking: false,
    category: 'other',
  },
  {
    id: 'mock-14',
    title: '熊本城の復旧工事が大きく進展 天守閣の修復完了間近',
    link: 'https://example.com/news/14',
    source: 'nhk',
    publishedAt: minutesAgo(300),
    prefectureCode: '43',
    prefectureName: '熊本県',
    isBreaking: false,
    category: 'other',
  },
  {
    id: 'mock-15',
    title: '政府 来年度予算案を国会に提出 総額115兆円',
    link: 'https://example.com/news/15',
    source: 'nhk',
    publishedAt: minutesAgo(50),
    prefectureCode: 'national',
    prefectureName: '全国',
    isBreaking: false,
    category: 'politics',
  },
  {
    id: 'mock-16',
    title: '香川県 うどん消費量が10年連続日本一に',
    link: 'https://example.com/news/16',
    source: 'nhk',
    publishedAt: minutesAgo(350),
    prefectureCode: '37',
    prefectureName: '香川県',
    isBreaking: false,
    category: 'other',
  },
  {
    id: 'mock-17',
    title: '鹿児島 桜島が小規模噴火 噴煙2000メートル',
    link: 'https://example.com/news/17',
    source: 'nhk',
    publishedAt: minutesAgo(15),
    prefectureCode: '46',
    prefectureName: '鹿児島県',
    isBreaking: false,
    category: 'disaster',
    ogpImageUrl: 'https://placehold.co/600x315/0a0a1a/ff8800?text=Sakurajima+Eruption',
  },
  {
    id: 'mock-18',
    title: '石川県能登地方 復興計画の進捗状況を報告',
    link: 'https://example.com/news/18',
    source: 'nhk',
    publishedAt: minutesAgo(400),
    prefectureCode: '17',
    prefectureName: '石川県',
    isBreaking: false,
    category: 'other',
  },
];
